class exchange (  
  $installerlocation = $exchange::params::installerlocation,
  $mode = $exchange::params::mode,
  $acceptexchangeserverlicense = $exchange::params::acceptexchangeserverlicense,
  $installwindowscomponents = $exchange::params::installwindowscomponents,
  $organizationname = $exchange::params::organizationname,
  $targetdir = $exchange::params::targetdir,
  $sourcedir = $exchange::params::sourcedir,
  $updatesdir = $exchange::params::updatesdir,
  $domaincontroller = $exchange::params::domaincontroller,
  $disableamfiltering = $exchange::params::disableamfiltering,
  $answerfile = $exchange::params::answerfile,
  $donotstarttransport = $exchange::params::donotstarttransport,
  $enableerrorreporting = $exchange::params::enableerrorreporting,
  $customerfeedbackenabled = $exchange::params::customerfeedbackenabled,
  $addumlanguage = $exchange::params::addumlanguage,
  $removeumlanguage = $exchange::params::removeumlanguage,
  $newprovisionserver = $exchange::params::newprovisionserver,
  $removeprovisionserver = $exchange::params::removeprovisionserver,
  $mdbname = $exchange::params::mdbname,
  $dbfilepath = $exchange::params::dbfilename,
  $logfolderpath = $exchange::params::logfolderpath,
  $activedirectorysplitpermissions = $exchange::params::activedirectorysplitpermissions,
  $tenantorganizationconfig = $exchange::params::tenantorganizationconfig,
  ){

  class { 'exchange::install':
    installerlocation               => $installerlocation,
    setupmode                       => $setupmode,
    roles                           => $roles,
    installwindowscomponents        => $installwindowscomponents,
    orgname                         => $orgname,
    targetdir                       => $targetdir,
    sourcedir                       => $sourcedir,
    updatesdir                      => $updatesdir,
    domaincontroller                => $domaincontroller,
    answerfile                      => $answerfile,
    donotstarttransport             => $donotstarttransport,
    enableerrorreporting            => $enableerrorreporting,
    customerfeedbackenabled         => $customerfeedbackenabled,
    addumlanguagepack               => $addumlanguagepack,
    removeumlanguagepack            => $removeumlanguagepack,
    newprovisionedserver            => $newprovisionedserver,
    removeprovisionedserver         => $removeprovisionedserver,
    mdbname                         => $mdbname,
    dbfilepath                      => $dbfilepath,
    logfolderpath                   => $logfolderpath,
    activedirectorysplitpermissions => $activedirectorysplitpermissions,
    tenantorganizationconfig        => $tenantorganizationconfig,
  }


